name: continuous integration - temporary

concurrency:
  group: temporary
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: ["*"]
    paths: ["./apps/temporary"]

env:
  REGISTRY: ghcr.io

jobs:
  continuous-integration:
    name: continuous integration
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install dependencies
        run: npm install
        working-directory: ./apps/temporary

      - name: build
        run: npm run build
        working-directory: ./apps/temporary

      - name: test
        run: npm test
        working-directory: ./apps/temporary

      - name: docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/amplication/temporary-example-kubernetes-deployment/temporary
          flavor: latest=true
          tags: |
            type=sha,prefix=sha-
            type=ref,event=branch
            type=ref,event=pr,prefix=pr-
            type=ref,event=tag,prefix=tag-
            type=raw,value=${{ github.run_id }},prefix=gh-

      - name: login to image repostiory
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: amplication
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: ./apps/temporary
          file: ./apps/temporary/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
